### ISSUE TITLE
Configuration value line removed when trying to use a recursive variable value

### ISSUE THREAD

**Issue by lebris** [Niktux/karma#88]
Wondering if karma allow to use recursive values (is this the right word for that ? variable depending on another variable value), i made a little test. 
It figured out that the resulting hydrated file the line in which the value from the recursive value should have been written.

The hydration didn't end with any exception, no error, only a php warning is shown. 
Then I realize that the line where the value from the recursive variable should have been written were missing.

Here's how to repeat the issue :

`config/test.yml-dist`

```
meat_name: <%meat.name%>
burger_name: <%burger.name%>
customer_name: <%customer.name%>
```

`env/master.conf`

```
[Variables]

meat.name:
    default = pony

burger.name:
    default = "<%meat.name%> with sparkles"

customer.name:
    default = prudman

```

Here is the ouput I got :

``` shell
$ vendor/bin/karma  hydrate
@@@@@@@@@@@@
@@@@@@@@@@@@
@@@@@@@@@@@@    K A R M A
@@@@@@@@@@@@               5.3.0
@@@@@@@@@@@@
@@@@@@@@@@@@

Hydrate config/ with dev values

[INFO]    Reading master.conf
PHP Warning:  Invalid argument supplied for foreach() in /tmp/test/vendor/niktux/karma/src/Karma/Hydrator.php on line 305
PHP Stack trace:
PHP   1. {main}() /tmp/test/vendor/niktux/karma/karma:0
PHP   2. Karma\Console->run() /tmp/test/vendor/niktux/karma/karma:7
PHP   3. Symfony\Component\Console\Application->run() /tmp/test/vendor/niktux/karma/src/Karma/Console.php:24
PHP   4. Symfony\Component\Console\Application->doRun() /tmp/test/vendor/symfony/console/Application.php:120
PHP   5. Symfony\Component\Console\Application->doRunCommand() /tmp/test/vendor/symfony/console/Application.php:189
PHP   6. Symfony\Component\Console\Command\Command->run() /tmp/test/vendor/symfony/console/Application.php:838
PHP   7. Karma\Command\ConfigureActionCommand->execute() /tmp/test/vendor/symfony/console/Command/Command.php:256
PHP   8. Karma\Command\Hydrate->launchConfigurationAction() /tmp/test/vendor/niktux/karma/src/Karma/Command/ConfigureActionCommand.php:75
PHP   9. Karma\Hydrator->hydrate() /tmp/test/vendor/niktux/karma/src/Karma/Command/Hydrate.php:28
PHP  10. Karma\Hydrator->hydrateFile() /tmp/test/vendor/niktux/karma/src/Karma/Hydrator.php:98
PHP  11. Karma\Hydrator->injectValues() /tmp/test/vendor/niktux/karma/src/Karma/Hydrator.php:119
PHP  12. Karma\Hydrator->injectListValues() /tmp/test/vendor/niktux/karma/src/Karma/Hydrator.php:216
[INFO]    1 files generated
```

Here's the content of the hydrated file `config/test.yml`

```
meat_name: pony
customer_name: prudman

```

The entire line where `burger_name` should be is missing.

Funny thing : using a non existing variable name in a variable value in the `.conf` file like the following enf up with and exception that can be confusing
`env/master.conf`

```
[Variables]

meat.name:
    default = pony

burger.name:
    default = "<%meat.plop%> with sparkles"

customer.name:
    default = prudman
```

``` shell
$ vendor/bin/karma  hydrate
@@@@@@@@@@@@
@@@@@@@@@@@@
@@@@@@@@@@@@    K A R M A
@@@@@@@@@@@@               5.3.0
@@@@@@@@@@@@
@@@@@@@@@@@@

Hydrate config/ with dev values

[INFO]    Reading master.conf



  [RuntimeException]          
  Unknown variable meat.plop  



hydrate [--cache] [--no-title] [-e|--env ENV] [-s|--system SYSTEM] [--dry-run] [-b|--backup] [-o|--override OVERRIDE] [-d|--data DATA] [--] [<sourcePath>]...

```

**Comment by Niktux** [comment]
"Recursive" is not supported by Karma. First step, we must add the missing sanity checks to have clean warnings and avoid confusive outputs.

Next step, should we add recursive values support ? 
I'm not very inclined to add it. The aim of Karma is not "doing anything we can with configuration files" but to promote proper way to handle configurations. I'm not sure recursive values are legitimate. At this time, I didn't see use case that need this feature. Correct configuration values organization and custom data should be enough.

Have you a real life use case that absolutely need such a feature ?

**Comment by Klemart3D** [comment]
Hi, I'm here because I'm wondering why this feature (the recursive value in _.conf_ file) was not added in **Karma**. For explanation, my use case :
I want to version (with _git_) a single karma global file : the _master.conf_ including only globals parameters without any personal data. This _master.conf_ file [includes] some other files gitignored (because of personal data) like _db.conf_ including all databases access and a _domain.conf_ including domain names and some local paths like this :

```
[variables]

localPath:
    dev = /path/to/the/dev/app/
    staging = /path/to/the/staging/app/
    prod = /path/to/the/production/app/
```

In my _master.conf_ I want a rule to generate dynamically an .htaccess depending of local path defined in _domain.conf_  :

```
[variables]

htaccess.authUserFile:
    staging = AuthUserFile "<%localPath%>.htpasswd"
    prod = AuthUserFile "<%localPath%>.htpasswd"
    default =
```
But as explained by @lebris it doesn't works. For me it will be a very productive feature because as explained in this [StackOverflow's question](http://stackoverflow.com/questions/6111627/how-to-use-a-relative-path-with-authuserfile-in-htaccess) :

> "It is not possible to use relative paths for AuthUserFile"

Can it be considered as an "absolutely need" feature ? :)
