### ISSUE TITLE
Hydrate an array with no value

### ISSUE THREAD

**Issue by Polydefis** [Niktux/karma#95]
When we hydrate an array with no value, we have an array with null an not a null value

Example :
mail.conf
```
mail.deliveryAddress:
	prod =
	default = [test@gmail.com]`
```

mail.yml-dist in default env
```
deliveryAddress:
    - test@gmail.com
```

mail.yml-dist in prod env
```
deliveryAddress:
    - 
```

**Comment by Niktux** [comment]
Release : 
https://github.com/Niktux/karma/releases/tag/5.4.0

Documentation :
http://www.karma-php.com/syntax/datatypes.html#controlling-list-hydratation
